name: Automatically merge approved Pull Requests

on:
  pull_request:
    types: ['labeled']
  schedule:
    - cron: '*/5 * * * 1-5' # Will run every 5 minutes, Monday to Friday

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as stale after 5 minutes
        uses: actions/stale@v8.0.0
        with:
          stale-issue-message: 'PR marked as stale'
          days-before-stale: 1
          days-before-close: 0
          stale-pr-message: 'PR marked as stale due to 5 minutes'
          stale-pr-label: stale

  approve:
    needs: stale
    if: ${{ contains( github.event.pull_request.labels.*.name, 'stale') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Check number of approvers'
        uses: taichi/approved-event-action@v1.2.1
        id: approved
        with:
          approvals: '1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    needs: approve
    if: ${{ needs.approve.outputs.isApproved == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Merge approved PR'
        uses: gr2m/merge-schedule-action@v1
        with:
          merge_method: rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
