name: 'Test SSM Github TF'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::562131571227:user/cec-assumeadmin
          aws-region: ap-southeast-1
          role-session-name: GHA-OIDC-CDK

      - name: Add hello SecureString to SSM
        uses: dwardu89/aws-ssm-parameter-store@v2.0.2
        with:
          ssm-path: "/cec-task"
          ssm-value: ${{ secrets.TEST_SECRET }}
          aws-region: ap-southeast-1
          ssm-value-type: "StringList"
